#!/bin/enc /python3 *org </*enc
#####################################
# Author =>>> Lunatic
# whatsap =>>> 082240074362
# Encrypt =>>> zlib,bzip3,encrown
####################################
LUNATIC="NWWMWKWKAKWKAKAMZNSNAMALALQLQMANWPSKSOWPWOOWOWKASNNSNSSNSNSNSNSNSNSMSMSMSKSKSKSKSKSKSKSKSMDNXNXNBDWLWLPAWOIWIWIEIEEIEIEIIEEIEIEOOEOEEOEOEOEOEOEOEOEOOEOEOEOEOEOENSNSNSN"
</="""
$$$
"""
LUNATIC=___!#)!#!#)#?!#)#0#!299202?!WOWIWKJWWJWKKWKWNSNAKLLALLLANNAKAANNSBXEUWPQPMDNDB"
\\\\/++///jebolin____dongs" ----> $LUNATIC "
